env:
  global:
  - secure: NxS1l7UNHiQLa1kjcddEKR8+Yc/ra8XVykccXddyTl//zQmd54Dqj4zzBcCOfkP5IBBlB+/smX5V0N4hrICQ2TLU9Vl6A5Kf+h5Rj1feavRSvi7YVt9jHTBjOpa98ImWjyBn52OmdMAy4AAyltxzNrRofhvpXyIDwjjmEEFpM+X8t+8T6Y3WdrEH3LAKhsWfVZ1WaOzDfyEZh9CNHgNaXrjh6kcdhgMU5BP8lah0ACE/2l0AO80DEPnfkzLcIWHhBbcHebSoUwyUPnvEPevj2mc4DuwcrjALWRbSkMFjQ5iKUb61Y/6mTxgx+rTz87LDWY+pzYAwVqQ2vHuE95Qu4ras2cC4oIesmLz8I+ieWxxpLeGl+1erEkYPF50B6lRYZg6eujUk7TcyQbuMKBBritOmsh+VLDEICMximAYHMbcDInvbn5ahFCFmT2bQh7weQ9FawhTUApZfcCWxLqIDmqSJuoQ4J9eJLtgFwSlql3TDSc+aAaZUUgdraMtnUw5Kf+bClGyLpwQxW5QNbSaU9GNa0hIWrrI4Px04TUn1bYEw9cI5IowyknN0be9wYR4ao2HbXJ3IGYDpZ+46p83+EUK2GT4i8x6fJLcDH4D92vUtZXKhMlaGMhLXRJddcOa//MQFm5l0oo/ymyqTOW7+K5Lv3NI0ZYTMwsxER53T5+E=
  - secure: Sn+zroUuMs/EKvBOV6v5bPhVkKt6zZpIO/nbQfC80peNg86Pi7DNVE9HVq9LjLwQXDOSuE+MPJB9skL7by+Iro6MIvP/IvBpuO+a6PeI+RhWBQs+bWIqskd5WCDPRk4fU4gHUQ4szCO+rkx06IV26EYp3Xw11dzwxduyDQeGNn6I54tlLusDjP7xeoix6V+1DSUBzJO+jL7d64Mh1SlxqaYyQ+jTDgBPp99q0nnlNRwSCOzlJg1xV63DaSIDVhvt6QLdE9RkFzZF1TTtHYqqu2b5squLc20A0nhMS3Tua9WG05zk7LadwzYPAm7Z77D0EoiNAFogEtFW/yaMOxTexaM40lT9+NchqxqkMIuoyL9sJdFlETZsy/nqwppV117XMGHsm9Unh+dWqerO9w8qgaWUgDlz3QCSm7xbLQdI1qkeLn+V6R4FA955EieRkqznKeXxBAYCaiqZiAGUdcEkn2ut+9k76Y//k2ac1QiVXeQq/7t7wMdQob7UCN68Vj44zOhDeNiJ/Bqk3yyaT3YjqFnPLEH+Qj/D2BNO7tRPQ0KH1qvLfOIBil+GJPBucQoBbA/vuOZvZeXIUpTZNP/IW+97U/yxXUNARWfEiLX6bw3eifQEknbdAa8T9HqUE42KSCVUQXDk0nAsszciLThbVkIEVCa6vl1uWx0dXY/Bl90=
  - secure: ZdCZc0JFp+Dm31Rw/9KRZzB3DjamrlT+v+kgwou8PB9ouGpJ2TD45DP3JqUoFElYEy1TBDlB7gB+PY9uaNtq+5b1KrOtX3DvoMv0Iqk6HMWtjzBptfrbeT150kkUrkwECRvfn04nni9CseXKjuTCZN+3liisxbaWjI4Z3TznAaSwLNGXQgQvpROItLRFOuTpyN4CldUOB0V6YIyfPANjpbmh4ijQND9WhCmw7qqYeMkYYx3blZNcrV7M4U0uJZ2/BqfIlcprGVrhBqnECzKQ6T9f8Pf9KNxn3LotfHsrqrVckFthojuvJqDmjKdx+9x1SHMxWTWvrWb+JJDIYjDnQppARXWQ/0+y0Jg34T6BOg/RMZej2Z6NIMbGa/SlHFsG13oBvTmTb6NOUQydQ2XakJi5c6Z0IJKGunP0Vcxo9H2ML0xsURW9NjUqrWSGs38ltWETF3HaEYWGHuZ9vFM1Pq7WhbdSKQQmPCqVyv1lKTuyp+wnO6JpzxE6Hc9Jx41tz5W+Pw/OeVBejZBs4tJ9Nkh7w6mY8zshoHlIx75ta6d+hc0SIZd63RqfR+ZsxgmLMx5hexoGciY67x6cXbJb86LmpZXgpX3DH4yi59aO88WMKqDsGmvgvB0zeZak6xDYLINT7Q5mhY/+A2SUxobN1VPMs2wrTnoZnSY2QCmSEEo=
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

install:
  - yarn install
  - curl -L -o /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.19/hugo_0.19_Linux-32bit.tar.gz
  - tar xvf /tmp/hugo.tar.gz -C /tmp/
  - mv /tmp/hugo_0.19_linux_386/hugo_0.19_linux_386 /usr/bin/hugo

after_success:
  - rm -r node_modules
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=crualbania/crubot
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO